### ISSUE TITLE
Error when moving strtip

### ISSUE THREAD

**Issue by nickberckley** [snuq/VSEQF#23]
This error is displayed every time I grab strip by the ends and try to move it, it still moves after the error, but it pops up every time. in 3.4 and 3.5 too

```
Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSE Quick Functions\grabs.py", line 606, in modal
    ripple_offset = move_sequences(context, self.starting_data, offset_x, offset_y, self.grabbed_sequences, ripple_pop=self.ripple_pop, fix_fades=False, ripple=self.ripple, move_root=False)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSE Quick Functions\grabs.py", line 175, in move_sequences
    move_sequence(context, sequence, offset_x, offset_y, data.select_left_handle, data.select_right_handle, data.channel, data.frame_start, data.frame_final_start, data.frame_final_end, ripple=ripple, fix_fades=fix_fades, only_fix=not move_root)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSE Quick Functions\grabs.py", line 128, in move_sequence
    move_sequence_right_handle(context, sequence, offset_x, new_channel, start_frame_final_end, fix_fades=fix_fades, only_fix=only_fix)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSE Quick Functions\grabs.py", line 94, in move_sequence_right_handle
    if new_end <= sequence.frame_final_start + 1 + sequence.frame_still_start:
AttributeError: 'ImageSequence' object has no attribute 'frame_still_start'. Did you mean: 'frame_final_start'?

```

**Comment by snuq** [comment]
This was an api break introduced a while back, i actually fixed it in the master but forgot to make a new release, oops! download the latest release or the master version and it should work fine.
