### ISSUE TITLE
Blender 3.5 crashes - VU meter needs "area"

### ISSUE THREAD

**Issue by 3dcinetv** [snuq/VSEQF#24]
Hello, today's release of Blender 3.5 solid release the console outputs this:
AttributeError: 'NoneType' object has no attribute 'areas'
Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSEQF-meter_only\__init__.py", line 55, in frame_step
    vu_meter.vu_meter_calculate(scene)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSEQF-meter_only\vu_meter.py", line 83, in vu_meter_calculate
    for area in bpy.context.screen.areas:
AttributeError: 'NoneType' object has no attribute 'areas'
Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSEQF-meter_only\__init__.py", line 55, in frame_step
    vu_meter.vu_meter_calculate(scene)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSEQF-meter_only\vu_meter.py", line 83, in vu_meter_calculate
    for area in bpy.context.screen.areas:
AttributeError: 'NoneType' object has no attribute 'areas'
Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSEQF-meter_only\__init__.py", line 55, in frame_step
    vu_meter.vu_meter_calculate(scene)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\VSEQF-meter_only\vu_meter.py", line 83, in vu_meter_calculate
    for area in bpy.context.screen.areas:
AttributeError: 'NoneType' object has no attribute 'areas'

...
and the error keeps repeating in the console until blender crashes.

**Comment by snuq** [comment]
this is very strange, i am using blender 3.5 as well and have not seen this error, and i cant imagine any reason why there would be no screen loaded, but the frame would be changing... are you running blender without an interface somehow?  or maybe what appears to be a modified version of vseqf is adding the handler for the vu meter in the wrong way?  have you tried using the unmodified version of vseqf?
