### ISSUE TITLE
Addon is unable to be installed using Blender 4.0

### ISSUE THREAD

**Issue by Matacrat** [snuq/VSEQF#29]
Here is the error report:
```
Traceback (most recent call last):
  File "D:\Tools\Models\Blender\App\Blender64\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "D:\Tools\Models\Blender\App\Blender64\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Tools\Models\Blender\Data\user_scripts\addons\VSEQF-4_0_1\__init__.py", line 55, in <module>
    from .addon_updater import Updater as updater
  File "D:\Tools\Models\Blender\Data\user_scripts\addons\VSEQF-4_0_1\addon_updater.py", line 30, in <module>
    import ssl
  File "D:\Tools\Models\Blender\App\Blender64\4.0\python\lib\ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: Module use of python311.dll conflicts with this version of Python.
```

**Comment by TestPilot02** [comment]
I'm not having this issue, am currently using it on 4.1.1 - If you are still having trouble I recommend uninstalling, then installing again with restarting blender in between.

If that does not work, close blender and navigate here:
C:\Users\<YOUR USERNAME GOES HERE>\AppData\Roaming\Blender Foundation\Blender\<YOUR VERSION OF BLENDER HERE>\scripts\addons

Delete the VSEQF-4_0_1 folder and then restart blender and re-install. If that still doesn't work, post here again.

**Comment by snuq** [comment]
Im not sure whats going on either, I have been using the addon without issue in Blender 4.0... and the error seems to be unrelated to my addon, but caused by the SSL module in your blender's python.  I think something is seriously weird with your blender python setup.
